name: Module Builder

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Vite build
        env:
          MODULE_VERSION: ${{ env.RELEASE_VERSION }}
          GH_PROJECT: ${{ github.repository }}
          GH_TAG: ${{ github.event.release.tag_name }}
        run: npm run build

      - name: Update module.json description
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./dist/module.json
          field: version
          value: ${{ steps.get_version.outputs.version-without-v }}

      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./module.zip ./*

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ env.MODULE_VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.zip, ./dist/module.json'